services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5000:8080" 
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=mydb;Uid=root;Pwd=yourpassword;

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "4444:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: